/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlayerPosition = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'z' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getPlayerPosition' : IDL.Func([], [PlayerPosition], ['query']),
  'loadWorld' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
  'saveWorld' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'updatePlayerPosition' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlayerPosition = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'z' : IDL.Float64,
  });
  
  return IDL.Service({
    'getPlayerPosition' : IDL.Func([], [PlayerPosition], ['query']),
    'loadWorld' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat8)], ['query']),
    'saveWorld' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'updatePlayerPosition' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };